### ISSUE TITLE
Add opt-in typing

### ISSUE THREAD

**Issue by alecvision** [codefortulsa/website#31]
Should be non-intrusive to avoid creating a barrier for new contributors, while keeping the door open for additional type-safety, code hinting, and self-documentation down the line. Documentation would also need updating to instruct newcomers on how to use (or ignore) the typing system.

**Comment by alecvision** [comment]
I put together an example [here](https://github.com/alecvision/website/tree/typescript). The `Seo.jsx` component and the `404.js` page have been left unmodified for a comparison.

**Comment by zenlex** [comment]
Closing as we're all TS in Next.
