### ISSUE TITLE
New tag proposals

### ISSUE THREAD

**Issue by alecvision** [codefortulsa/website#41]
I propose adding two new sets of issue tags which.

 - A set of tags for each technology used
   * stack:React
   * stack:Gatsby
   * stack:Gatsby-Plugin
   * stack:Graphql
   * stack:TypeScript
  
- A set of priority tags 
   * priority:Critical
   * priority:High
   * priority::Medium
   * priority:Low
   * priority:Defer

The idea here is to guide contributors towards issues where they can have the most impact, as well as provide a framework to help future maintainers and organizers. Creating a tag for each part of the technology stack is meant to reduce onboarding requirements for new contributors by encouraging organizers to scope issues to as few technology components as possible.

**Comment by zenlex** [comment]
Took a modified subset of this and implemented it for now. Going to suggest we don't need 'Critical' for this project, and that we use the default existing 'wontfix' label in place of Defer.
